import type { PassColors } from "./types";

export type Preset = {
  id: string;
  name: string;
  colors: PassColors;
};

export const PRESETS: Preset[] = [
  {
    id: "frontier",
    name: "Frontier",
    colors: {
      appBg: "#f4f4f4",
      headerBg: "#0e6e3a",
      headerText: "#ffffff",
      passBg: "#3cbef0",
      passText: "#2a2a2a",
      passSubText: "#2a2a2a",
      cardBg: "#ffffff",
      cardText: "#1f1f1f",
      cardSubText: "#1f1f1f",
      accent: "#1f1f1f",
      statusBg: "#e6f4ea",
      statusText: "#0e6e3a",
      dotActive: "#0e6e3a",
      dotInactive: "#c9c9c9",
    },
  },
  {
    id: "delta",
    name: "Delta",
    colors: {
      appBg: "#f4f4f4",
      headerBg: "#003366",
      headerText: "#ffffff",
      passBg: "#c8102e",
      passText: "#ffffff",
      passSubText: "#ffe1e6",
      cardBg: "#ffffff",
      cardText: "#1f1f1f",
      cardSubText: "#444444",
      accent: "#ffffff",
      statusBg: "#e6eef7",
      statusText: "#003366",
      dotActive: "#003366",
      dotInactive: "#cccccc",
    },
  },
  {
    id: "southwest",
    name: "Southwest",
    colors: {
      appBg: "#fff8e6",
      headerBg: "#304cb2",
      headerText: "#ffffff",
      passBg: "#f9b612",
      passText: "#1d1d1d",
      passSubText: "#3a3a3a",
      cardBg: "#ffffff",
      cardText: "#1f1f1f",
      cardSubText: "#444444",
      accent: "#e31837",
      statusBg: "#ffe6c2",
      statusText: "#8a4b00",
      dotActive: "#e31837",
      dotInactive: "#d8d8d8",
    },
  },
  {
    id: "jetblue",
    name: "JetBlue",
    colors: {
      appBg: "#eef6fb",
      headerBg: "#0033a0",
      headerText: "#ffffff",
      passBg: "#00a1e0",
      passText: "#ffffff",
      passSubText: "#e6f6ff",
      cardBg: "#ffffff",
      cardText: "#0033a0",
      cardSubText: "#3a3a3a",
      accent: "#0033a0",
      statusBg: "#e6f0fa",
      statusText: "#0033a0",
      dotActive: "#0033a0",
      dotInactive: "#cfd9eb",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    colors: {
      appBg: "#0b0d12",
      headerBg: "#111827",
      headerText: "#e5e7eb",
      passBg: "#1f2937",
      passText: "#f9fafb",
      passSubText: "#9ca3af",
      cardBg: "#0f1422",
      cardText: "#f9fafb",
      cardSubText: "#9ca3af",
      accent: "#22d3ee",
      statusBg: "#022c22",
      statusText: "#34d399",
      dotActive: "#22d3ee",
      dotInactive: "#374151",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    colors: {
      appBg: "#fff3ec",
      headerBg: "#7c2d12",
      headerText: "#fff7ed",
      passBg: "#fb7185",
      passText: "#1f1f1f",
      passSubText: "#4a1d1d",
      cardBg: "#ffffff",
      cardText: "#1f1f1f",
      cardSubText: "#4a1d1d",
      accent: "#7c2d12",
      statusBg: "#fde68a",
      statusText: "#7c2d12",
      dotActive: "#fb7185",
      dotInactive: "#fbcfe8",
    },
  },
];
